"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../app/components/_nav";
import SideBar from "../app/(home)/sideBar";
import { useState } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient();

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [display, setDisplay] = useState(false);

  const toggleDisplay = () => {
    setDisplay(!display);
  };

  const closeDisplay = () => {
    setDisplay(false);
  };

  return (
    <html lang="en">
      <body className="sm:overflow-hidden">
        <QueryClientProvider client={queryClient}>
          <Nav toggleDisplay={toggleDisplay} />
          {display ? (
            <>
              <div className="sm:hidden">
                <SideBar closeDisplay={closeDisplay} />
              </div>
            </>
          ) : (
            <div>{children}</div>
          )}
        </QueryClientProvider>
      </body>
    </html>
  );
}
